# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ddfbd1158aee6d78ddb66269f5c48e7b2778061d98e723d2a93e3a77f7306de2558432a01ba3b4243254d9bef165e01b233a2dafaa0538e9ec6b03e53d19a64

test:
  secret_key_base: e8ef5cc13e31b774eb89d6e78a09e4fda446122880897b026700938bafaa9a7d31dae1cab2280ea337bf3317f0528112d8e7f125695f14453c1d9543cd7701ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
